apiVersion: v1
kind: Secret
metadata:
  name: factoryadminsecrets
  namespace: {{ .Release.Namespace }}
data:
  FACTORY_ADMIN_USER: {{ .Values.factory_admin_secrets.user | b64enc }}
  FACTORY_ADMIN_PASSWORD: {{ .Values.factory_admin_secrets.password | b64enc }}
